server:
  port: 7001
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        service-name: consul-consumer
        health-check-path: /health
        health-check-interval: 15s